### ISSUE TITLE
can't load any SOFA file with latest master 

### ISSUE THREAD

**Issue by the-drunk-coder** [hoene/libmysofa#99] opened 2020-01-17 10:55 UTC
I'm not sure if this duplicates #97, but as of the latest master branch (commit c31120a4ddfe3fc705cfdd74da7e884e1866da85), I can't load any SOFA file any more. 

I've been building from the `added-multithread-test` branch before, and didn't encounter any problems. 

This concerns some common public SOFA files, like the HRIR_L2702_* series (published here: https://sofacoustics.org/data/database/fhk/), as well as the files my colleagues created with Matlab.

**Comment by hoene** [comment] 2020-01-17 12:29
Hi, just wait a bit. The problem is already solved in the branch “superblock”.

 

Von: the-drunk-coder <notifications@github.com> 
Gesendet: Freitag, 17. Januar 2020 11:56
An: hoene/libmysofa <libmysofa@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [hoene/libmysofa] can't load any SOFA file with latest master (#99)

 

I'm not sure if this duplicates #97 <https://github.com/hoene/libmysofa/issues/97> , but as of the latest master branch (commit  <https://github.com/hoene/libmysofa/commit/c31120a4ddfe3fc705cfdd74da7e884e1866da85> c31120a), I can't load any SOFA file any more.

I've been building from the added-multithread-test branch before, and didn't encounter any problems.

This concerns some common public SOFA files, like the HRIR_L2702_* series (published here: https://sofacoustics.org/data/database/fhk/), as well as the files my colleagues created with Matlab.

**Comment by the-drunk-coder** [comment] 2020-01-17 13:22
Thanks, i'll check it out !

**Comment by hoene** [comment] 2020-01-17 15:36
Fixed in 46a7e0065c573c9341ad85c390958294217465d4

**Closed by hoene** 2020-01-17 15:36 UTC
