### ISSUE TITLE
libmysofa crossbuild build break

### ISSUE THREAD

**Issue by AurelioSilver** [hoene/libmysofa#39] opened 2017-11-27 12:27 UTC
CMake Error at CMakeLists.txt:60:
  Parse error.  Expected "(", got quoted argument with text "lib/pkgconfig".
-- Configuring incomplete, errors occurred!

See here: https://github.com/rdp/ffmpeg-windows-build-helpers/issues/281

**Comment by umlaeute** [comment] 2017-11-27 19:36
libmysofa is auto-built on AppVeyor (W32) and Travis-CI (linux and OSX) to catch such errors, and all the tests succeeded.

please be more specific about what you did to make this error happen.

from the https://github.com/rdp/ffmpeg-windows-build-helpers/issues/281 issue it seems that you are modifying the CMakeLists.txt file, causing the error (a blind `sed -i.bak "/^install/,+1d" CMakeLists.txt` will remove the first line of a multi-line stanza, thus breaking the syntax of the cmake-file).

to repeat my question from there:

-    Is `sed "/^install/,+1d" CMakeLists.txt` the standard way to enable cross-builds for CMake-projects?
-    Where is this documented?
-    What is this trying to solve?

Maybe the problem you are trying to solve can be fixed in a more robust way than (blindly) removing lines from the CMakefile.

**Comment by umlaeute** [comment] 2017-11-27 19:40
btw, the CI-builds do not do any "cross builds".

however, from your example i don't see how you do a cross-build either:  could you post a **minimal** example to actually do a cross-build libmysofa (and which breaks in the way you describe it)?

**Comment by AurelioSilver** [comment] 2017-11-27 19:57
Well, I just reported the bug because some people do not report it upstream where usually bugs/issues should be fixed, if possible.

Just try the script from the ffmpeg windows build helpers repo. I actually use a VM with Centos 7 OS to build ffmpeg for windows with these scripts.

I'm more a user than a dev. So I can not judge if its a "bug" from libmysofa or of the scripts.

**Comment by AurelioSilver** [comment] 2017-11-27 20:34
If I read it correctly the script tries to remove all lines from CMakeLists which contains the command install in order to build a library only. But because now the a new install command spanning multiple lines was introduced the sed fails to produce a valid CMakeLists? 

In that case it's not really your problem and the issue should be fixed in the script.

Sorry for the noise.

**Comment by umlaeute** [comment] 2017-11-27 20:51
np. sorry if i came across rude, i just tried to squeeze as much information out of you on the actual issue (to see whether the problem is on my side or on the ffmpeg-windows-build-helpers#281  side)

**Comment by umlaeute** [comment] 2017-11-28 08:43
closing this, as the problem is really on the consumer's side.

**Closed by umlaeute** 2017-11-28 08:43 UTC
